#%RAML 0.8
title: hybris Service Archetype
baseUri: http://localhost/
version: v1
mediaType:  application/json

schemas:
  - templates: !include schemas/templates.json
  - template: !include schemas/template.json
  - templateData: !include schemas/templateData.json
  - templateContext: !include schemas/templateContext.json
  - templateMap: !include schemas/templateMap.json
  - error: !include https://api.yaas.io/patterns/v1/schema-error-message.json

traits:
  - !include https://api.yaas.io/patterns/v2/trait-yaas-aware.yaml

resourceTypes:
  - !include https://api.yaas.io/patterns/v2/resource-type-element.yaml
  - !include https://api.yaas.io/patterns/v1/resource-type-collection.yaml

/templates:
  type: collection
  is: [yaasAware]
  get:
    description: Gets all templates
    responses:
      200:
        body:
          application/json:
            example: !include examples/templates-example.json
  post:
    body:
      application/json:
        example: !include examples/template-example.json

  /{templateId}:
    type: element
    is: [yaasAware]
    uriParameters:
      templateId:
        description: the id of the template to work on
        example: 784hti8ey
        type: string
    get:
      description: Gets a template
      responses:
        200:
          body:
            application/json:
              example: !include examples/template-example.json

    put:
      description: Updates a template
      body:
        application/json:
          example: !include examples/template-example.json
    post:
      body:
        multipart/form-data:
          formParameters:
            file:
              type: file
    delete:
      description: Deletes a template

/generate:
  is: [yaasAware]
  post:
    description: generatePdf file
    body:
      application/json:
        schema: templateData
    responses:
            200:
              body:
                application/pdf:
                  example: !include examples/generatedFile-example.pdf